<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Agregar factura</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>facturas">Volver
					<img src="<?php echo $path?>public/img/system/volver.png" alt="volver"/>
				</a> /
				<a href="<?php echo $path ?>facturas/agregar" title="Agregar factura">
					Agregar otra factura
					<img src="<?php echo $path?>public/img/system/nuevo.png" alt="nuevo"/>
				</a>
			</div>
		</div>
		<?php switch($option) {
				case 'captura': ?>
				<form action="<?php echo $path ?>facturas/agregar" id="frm_agregar" method="post">
					<input type="hidden" name="ejercicio_id" id="ejercicio_id" value="<?php echo $ejercicio_id ?>" />

					<fieldset>
						<legend>Fiscal</legend>
                        <label for="clave">Folio</label><br/>
						<?php $factura = new Factura(); ?>
						<?php echo $factura->obtenFolio(); ?>
						<br/>
						<br/>
						<?php $hoy = new Datetime(); ?>
                        <label for="clave">Fecha</label>
                        <br/>
                        <input name="fecha"
                                id="fecha" 
                                value="<?php echo $hoy->format("d/m/Y"); ?>" 
                                size="10" 
                                maxlength="10" 
                                class="_fecha_" 
                                readonly="readonly" />
                        <br/>
                        <br/>
						<label for="clave">RFC</label>
						<br />
						<select name="dependencia_id" id="dependencia_id" >
						    <option></option>
						    <?php foreach ($dependencias as $dependencia) { ?>
								<option value="<?php echo $dependencia->id ?>">
								    <?php echo $dependencia->nombre; ?></option>
							<?php } ?>
						</select>
						<br />
						<br />
                        <div id="fiscales">

                        </div>
					</fieldset>
					<div class="divisor"></div>

					<fieldset style="margin-left: -50px;">
					    <legend>Conceptos</legend>
					    <div class="tablik">
					    <table id="tblConceptos">
					        <tr>
                                <th>
                                    <a  title="Seleccionar todas las filas"
                                        class="swAllRows"
                                        href="#">
                                        <img src="<?php echo $path?>public/img/system/ver.png" alt="Seleccionar todo"/>
                                    </a>
                                </th>
                                <th>Clave</th>
                                <th>Descripción</th>
					            <th>Cantidad</th>
                                <th>Unitario</th>
                                <th>Monto</th>
					        </tr>
					        <tr class="selected">
					            <td class="centro">
                                        <input type="checkbox"
                                               name="chktam"
                                               checked="checked"
                                               class="switch" />
                                    </td>
                                <td class="centro">
                                    <input type="text" size="12" maxlength="20"
                                            name="clave[]" class="clave"/>
                                </td>


                                <td class="centro">
                                    <input type="text" size="70" maxlength="300"
                                            name="concepto[]" class="concepto"/>

                                </td>

                                <td class="centro">
                                    <input type="text" size="4" maxlength="3"
                                            name="cantidad[]" class="cantidad centro _entero_"/>
                                </td>


                                <td class="centro">
                                    <input type="text" size="12" maxlength="12"
                                            name="unitario[]" class="unitario numero _real_"/>
                                </td>

                                <td class="centro">
                                    <input type="text" size="12" maxlength="12"
                                            name="costo[]" class="monto costo numero _real_" readonly="readonly"/>
                                </td>
					        </tr>
					    </table>
					    <br />
					    <div class="buttons">
                                <a href="#" class="addRow">
                                    <img src="<?php echo $path . 'img/system/mas.png' ?>" alt="agregar" title="Agregar fila" />
                                </a>
                                <a href="#" class="delRow">
                                    <img src="<?php echo $path . 'img/system/menos.png' ?>" alt="eliminar" title="Eliminar fila" />
                                </a>
                            </div>
					    </div>

                        <div style="margin-left: 800px;">
                        <table>
                            <tr>
                                <th>Subtotal</th>
                                <td>
                                    <input type="text" size="12" maxlength="12"
                                            name="subtotal" class="total-monto subtotal numero"
                                            readonly="readonly"
                                            id="subtotal"/>
                                </td>
                            </tr>
                            <tr>
                                <th>IVA</th>
                                <td>
                                    <input type="text" size="12" maxlength="12"
                                            name="iva" class="iva numero"
                                            readonly="readonly"
                                            id="iva"/>
                                </td>
                            </tr>
                            <tr>
                                <th>Total</th>
                                <td>
                                    <input type="text" size="12" maxlength="12"
                                            name="total" class="total numero"
                                            readonly="readonly"
                                            id="total"/>
                                </td>
                            </tr>
                        </table>
                        </div>
					</fieldset>
					
					
                    <fieldset>
                        <legend>Observaciones</legend>
                            <textarea name="observaciones" id="observaciones" cols="100" rows="5" class="_opcional_"></textarea>
                        </div>
                    </fieldset>

					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Agregar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />
					La informaci&oacute;n de la factura se agreg&oacute; correctamente
				</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error">
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>