<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Editar factura</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>facturas">Volver
					<img src="<?php echo $path?>public/img/system/volver.png" alt="volver"/>
				</a> /
				<a href="<?php echo $path ?>facturas/agregar" title="Agregar factura">
					Agregar otra factura
					<img src="<?php echo $path?>public/img/system/nuevo.png" alt="nuevo"/>
				</a> /

                <a href="<?php echo $path ?>facturas/ver/<?php echo $factura->id; ?>" title="Ver factura">
                    Ver factura
                    <img src="<?php echo $path?>public/img/system/ver.png" alt="ver"/>
                </a> /
                <a href="<?php echo $path ?>facturas/control/<?php echo $factura->id; ?>" title="Control factura">
                    Cambiar estado
                    <img src="<?php echo $path?>public/img/system/estado.png" alt="control"/>
                </a> /
                <a target="_BLANK" href="<?php echo $path; ?>facturas/imprimir/<?php echo $factura->id; ?>"  title="Imprimir">
                    Imprimir
                    <img src="<?php echo $path ?>public/img/system/imprimir.png" alt="imprimir"/>
                </a>

			</div>
		</div>
		<?php switch($option) {
				case 'captura': ?>
				<form action="<?php echo $path ?>facturas/editar" id="frm_editar" method="post">
					<input type="hidden" name="factura_id" id="factura_id" value="<?php echo $factura->id ?>" />
					<input type="hidden" name="fdependencia_id" id="fdependencia_id" value="<?php echo $factura->dependencia_id ?>" />

					<fieldset>
						<legend>
							Factura <?php echo $factura->folio; ?>
						</legend>
						<label for="clave">Fecha</label>
                        <br/>
                        <input name="fecha"
                               id="fecha"
                               value="<?php echo Utils::convierteFecha(substr($factura->fecha,0,10)); ?>"
                               size="10"
                               maxlength="10"
                               class="_fecha_"
                               readonly="readonly" />
                        <br/>
                        <br/>
						<label for="metodopago_id">M&eacute;todo de pago</label>
						<br />
                        <select name="metodopago_id" id="metodopago_id" >
						    <?php foreach ($metodospago as $metodo) { ?>
								<option value="<?php echo $metodo->id ?>"
									<?php if( $factura->metodopago_id == $metodo->id ){?>
									selected="selected"
									<?php } ?>>
								    <?php echo utf8_encode( $metodo->nombre ); ?></option>
							<?php } ?>
						</select>
						<br />
						<br />
						<div id="ctapago_div" 
							 <?php if( $factura->metodopago_id <= 2 ){ ?>style="display:none"<?php } ?>>
							<label for="ctapago">
								N&uacute;mero de cuenta del pago
								<span class="sub2">
									(&Uacute;ltimos 4 d&iacute;gitos)
								</span>
							</label>
							<br />
	                        <input type="text"
	                        	   name="ctapago"
	                               id="ctapago" 
	                               value="<?php echo $factura->ctapago ?>"
	                               size="4" 
	                               maxlength="4"
	                               <?php if( $factura->metodopago_id <= 2 ){ ?>
	                               	disabled="disabled" 
	                               <?php } ?> />
						</div>
						<label for="dependencia_id">Cliente</label>
						<br />
						<select name="dependencia_id" id="dependencia_id" >
						    <option></option>
						    <?php foreach ($dependencias as $dependencia) { ?>
								<option value="<?php echo $dependencia->id ?>">
								    <?php echo $dependencia->nombre; ?></option>
							<?php } ?>
						</select>
						<br />
						<br />
                        <div id="fiscales">

                        </div>
					</fieldset>
					<div class="divisor"></div>

					<fieldset style="margin-left: -50px;">
					    <legend>Conceptos</legend>
					    <div class="tablik">
					    <table id="tblConceptos">
					        <tr>
                                <th>
                                    <a  title="Seleccionar todas las filas"
                                        class="swAllRows"
                                        href="#">
                                        <img src="<?php echo $path?>public/img/system/ver.png" alt="Seleccionar todo"/>
                                    </a>
                                </th>
                                <th>Clave</th>
                                <th>Descripción</th>
					            <th>Cantidad</th>
                                <th>Unitario</th>
                                <th>Monto</th>
					        </tr>
					        <?php
					           $conceptos = $factura->conceptos();
					         ?>
					         <?php foreach ($conceptos as $concepto) { ?>
					        <tr class="selected">
					            <td class="centro">
                                        <input type="checkbox"
                                               name="chktam"
                                               checked="checked"
                                               class="switch" />
                                    </td>
                                <td class="centro">
                                    <input type="text" size="12" maxlength="20"
                                            name="clave[]" class="clave"
                                            value="<?php echo $concepto->clave; ?>"/>
                                </td>


                                <td class="centro">
                                    <input type="text" size="70" maxlength="300"
                                            name="concepto[]" class="concepto"
                                            value="<?php echo htmlentities( utf8_decode( $concepto->descripcion ) ); ?>"/>

                                </td>

                                <td class="centro">
                                    <input type="text" size="4" maxlength="3"
                                            name="cantidad[]" class="centro cantidad _entero_"
                                            value="<?php echo $concepto->cantidad; ?>"/>
                                </td>


                                <td class="centro">
                                    <input type="text" size="12" maxlength="12"
                                            name="unitario[]" class="unitario numero _real_"
                                            value="<?php echo $concepto->unitario; ?>"/>
                                </td>

                                <td class="centro">
                                    <input type="text" size="12" maxlength="12"
                                            name="costo[]" class="costo numero monto _real_"
                                            readonly="readonly"
                                            value="<?php echo $concepto->monto; ?>"/>
                                </td>
					        </tr>
					        <?php } ?>
					    </table>
					    <br />
					    <div class="buttons">
                                <a href="#" class="addRow">
                                    <img src="<?php echo $path . 'img/system/mas.png' ?>" alt="agregar" title="Agregar fila" />
                                </a>
                                <a href="#" class="delRow">
                                    <img src="<?php echo $path . 'img/system/menos.png' ?>" alt="eliminar" title="Eliminar fila" />
                                </a>
                            </div>
					    </div>

                        <div style="margin-left: 800px;">
                        <table>
                            <tr>
                                <th>Subtotal</th>
                                <td>
                                    <input type="text" size="12" maxlength="12"
                                            name="subtotal" class="total-monto numero subtotal"
                                            id="subtotal"  readonly="readonly"
                                            value="<?php echo $factura->subtotal; ?>"/>
                                </td>
                            </tr>
                            <tr>
                                <th>IVA</th>
                                <td>
                                    <input type="text" size="12" maxlength="12"
                                            name="iva" class="numero iva"
                                            id="iva" readonly="readonly"
                                            value="<?php echo $factura->iva; ?>"/>
                                </td>
                            </tr>
                            <tr>
                                <th>Total</th>
                                <td>
                                    <input type="text" size="12" maxlength="12"
                                            name="total" class="total"
                                            id="total" readonly="readonly"
                                            value="<?php echo $factura->total; ?>"/>
                                </td>
                            </tr>
                        </table>
                        </div>
					</fieldset>


                    <fieldset>
                        <legend>Observaciones</legend>
                            <textarea name="observaciones" id="observaciones" cols="100" rows="5" class="_opcional_"><?php echo $factura->observaciones; ?></textarea>
                    </fieldset>


					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Editar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />
					La informaci&oacute;n de la factura se agreg&oacute; correctamente
				</p>
			<?php  break; ?>
			<?php case 'error':
				  default:
			?>
				<p class="error">
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>