<?php $path = KUMBIA_PATH;?>
<?php switch($option) {
    case 'exito':

        Kumbia :: import( 'app.reportes.*' );

        $xls = new XLSFactura( array( $factura ) );
        $xls->generar();

      break;

    case 'error':
              default:
        ?>
            <div id="primary">
                <div class="content">
                    <h1>Imprimir factura</h1>
                    <div id="options-bar">
                        <div id="options">
                            <a href="<?php echo $path ?>facturas">Volver
                                <img src="<?php echo $path?>public/img/system/volver.png" alt="volver"/>
                            </a>
                        </div>
                    </div>
                    <div class="error">
                        <br />
                        <?php echo $error ?>
                    </div>
                </div>
            </div>
    <?php  break; ?>
<?php } ?>