<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Cambiar password</h1>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>sistema/password/" id="frm_pass" method="post">
					<fieldset>
						<legend>Nuevos datos de acceso</legend>
						<label for="pass">Password anterior</label><br />
						<input type="password" name="pass" id="pass" size="32" maxlength="32" /><br />
						<label for="pass">Nuevo password</label><br />
						<input type="password" name="pass2" id="pass2" size="32" maxlength="32" /><br />
						<label for="pass2">Confirmar password</label><br />
						<input type="password" name="pass3" id="pass3" size="32" maxlength="32" /><br />
					</fieldset>
					<div class="divisor"></div>
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Aceptar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />Su password de acceso se cambi&oacute; correctamente.
					<br />
					<a href="<?php echo $path ?>sistema/configuracion">Continuar</a>
				</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error">
					<br />
					<?php echo $error ?>
					<br />
					<a href="<?php echo $path ?>sistema/configuracion">Continuar</a>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>