<?php $css_path = KUMBIA_PATH . 'css/' ?>
<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=utf-8' />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <title>Publicidad / <?php echo ucfirst($controlador) ?></title>
  <link rel="shortcut icon" href="<?php echo "http://" . $_SERVER["SERVER_NAME"].KUMBIA_PATH . 'favicon.ico'?>" />
  <link href="<?php echo $css_path ?>system/tripoli.base.css" type="text/css" rel="stylesheet" />
  <link href="<?php echo $css_path ?>system/tripoli.type.css" type="text/css" rel="stylesheet" />
  <link href="<?php echo $css_path ?>system/tripoli.visual.css" type="text/css" rel="stylesheet" />
  <link href="<?php echo $css_path ?>system/tripoli.layout.css" type="text/css" rel="stylesheet" />
  <!--[if IE]><link rel="stylesheet" type="text/css" href="<?php echo $css_path ?>system/tripoli.base.ie.css" /><![endif]-->
 <?php content() ?>
</html>