<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Agregar dependencia s</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>externas">Volver
					<img src="<?php echo $path?>public/img/system/volver.png" alt="volver"/>
				</a> /
				<a href="<?php echo $path ?>externas/agregar" title="Agregar dependencia">
					Agregar otra dependencia 
					<img src="<?php echo $path?>public/img/system/nuevo.png" alt="nuevo"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>externas/agregar" id="frm_agregar" method="post">
					<input type="hidden" name="ejercicio_id" id="ejercicio_id" value="<?php echo $ejercicio_id ?>" />
					<fieldset>					
						<legend>Datos</legend>
						<label for="clave">Clave</label>
						<br />
						<input type="text" name="clave" id="clave" size="12" maxlength="12" />
						<br />
						<br />
						<label for="nombre">Nombre</label>
						<br />
						<input type="text" name="nombre" id="nombre" size="30" maxlength="256" />
						<br />
						<br />
					</fieldset>
					<div class="divisor"></div>
					
					<fieldset>					
						<legend>Fiscal</legend>
						<label for="clave">RFC</label>
						<br />
						<input type="text" name="rfc" id="rfc" size="20" maxlength="20" />
						<br />
						<br />
						<label for="razon">Raz&oacute;n social</label>
						<br />
						<input type="text" name="razon" id="razon" size="30" maxlength="255" />
						<br />
						<br />
						<label for="domicilio">Domicilio</label>
						<br />
						<input type="text" name="domicilio" id="domicilio" size="30" maxlength="255" />
						<br />
						<br />
						<label for="colonia">Colonia</label>
						<br />
						<input type="text" name="colonia" id="colonia" size="30" maxlength="255" />
						<br />
						<br />
						<label for="cp">C&oacute;digo postal</label>
						<br />
						<input type="text" name="cp" id="cp" size="20" maxlength="20" />
						<br />
						<br />
						<div class="localizacion_estado">
						</div>
					</fieldset>
					<div class="divisor"></div>
					
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Agregar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />
					La informaci&oacute;n de la dependencia se agreg&oacute; correctamente
				</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error">
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>