<?php $path = KUMBIA_PATH; ?>
		<?php switch($option) { 
				case 'captura': ?>
				<?php $fiscal = $dependencia->fiscal(); ?>
                <?php $municipio = $fiscal->municipio(); ?>
                <?php $edo = $municipio->edo(); ?>
				RFC: <?php echo $fiscal -> rfc; ?> <br/>
                Razón social: <?php echo $fiscal -> razon; ?> <br/>
                Domicilio: <?php echo $fiscal -> domicilio; ?> <br/>
                Colonia: <?php echo $fiscal -> colonia; ?> <br/>
                C.P.: <?php echo $fiscal -> cp; ?> <br/>
                Municipio: <?php echo $municipio -> nombre; ?> <br/>
                Estado: <?php echo $edo -> nombre; ?> <br/>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />
					La dependencia se elimin&oacute; correctamente.</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error">
					Ha ocurrido un error al intentar eliminar la dependencia.
					<br />
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>