<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Agregar usuario</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>usuarios">Volver
				<img src="<?php echo $path?>public/img/system/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>usuarios/agregar" id="frm_agregar" method="post">
					<fieldset>
						<legend>Personal</legend>
						<label for="nombre">Nombre</label><br />
						<input type="text" name="nombre" id="nombre" size="30" maxlength="30" /><br />
						<label for="ap">Apellido paterno</label><br />
						<input type="text" name="ap" id="ap" size="20" maxlength="20" /><br />
						<label for="am">Apellido materno</label><br />
						<input type="text" name="am" id="am" size="20" maxlength="20" /><br />
						<label for="mail">Correo electr&oacute;nico</label><br />
						<input type="text" name="mail" id="mail" size="30" maxlength="80" />
					</fieldset>
					<div></div>
					<fieldset>
						<legend>Acceso</legend>
						<label for="login">Login</label><br />
						<input type="text" name="login" id="login" size="16" maxlength="16" />
						<img id="spinner" src="<?php echo $path ?>/public/img/system/spinner.gif" style="display:none"/>
						<br />
						<div id="check" class="check"></div>
						<label for="pass">Password</label><br />
						<input type="password" name="pass" id="pass" size="32" maxlength="32" /><br />
						<label for="pass2">Confirmar password</label><br />
						<input type="password" name="pass2" id="pass2" size="32" maxlength="32" /><br />
						<label for="grupo">Grupo</label><br />
						<select name="grupo[]" id="grupo">
									<option></option>		
						<?php if(is_array($grupos)){
								foreach($grupos as $id => $grupo){
						?>
									<option value="<?php echo $id ?>"><?php echo ucfirst($grupo) ?></option>		
						<?php 	}
							  } 
						?>
						</select>
						<img id="spinner1" src="<?php echo $path ?>/public/img/system/spinner.gif" style="display:none"/>
						<div id="acceso" class="acceso"></div>
					</fieldset>
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="agregar" value="Agregar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />El usuario se agreg&oacute; correctamente</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error"><br />Ha ocurrido un error al intentar agregar el usuario
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>