<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Cambiar password del usuario <?php echo $usuario->login?></h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>usuarios">Volver
				<img src="<?php echo $path?>public/img/system/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>usuarios/password/" id="frm_pass" method="post">
					<fieldset>
						<legend>Nuevos datos de acceso</legend>
						<input type="hidden" name="id" id="id" value="<?php echo $usuario->id ?>" />
						<label for="pass">Password</label><br />
						<input type="password" name="pass" id="pass" size="32" maxlength="32" /><br />
						<label for="pass2">Confirmar password</label><br />
						<input type="password" name="pass2" id="pass2" size="32" maxlength="32" /><br />
					</fieldset>
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Aceptar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info"><br />El password del usuario se cambi&oacute; correctamente.</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error"><br />Ha ocurrido un error al intentar cambiar el password del usuario.
				<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>