<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Datos del usuario <?php echo $usuario->login?></h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>usuarios">Volver
				<img src="<?php echo $path?>public/img/system/volver.png"/>
				</a>
				<?php if($usuario->id != ''){?>		
		 			 / <a href="<?php echo $path . 'usuarios/editar/' . $usuario->id?>"
					   alt="Editar datos del usuario" title="Editar datos del usuario">
					   Editar 
					   <img src="<?php echo $path?>public/img/system/editar.png" />
					</a> 
					 / <a href="<?php echo $path . 'usuarios/password/' . $usuario->id?>"
					   alt="Cambiar el password del usuario" title="Cambiar password del usuario">
					   Cambiar password
					   <img src="<?php echo $path?>public/img/system/pass.png" />
					</a>
					 / <a href="<?php echo $path . 'usuarios/eliminar/' . $usuario->id?>"
					   alt="Eliminar toda la informacion del usuario" title="Eliminar toda la informacion del usuario">
					   Eliminar
					   <img src="<?php echo $path?>public/img/system/eliminar.png" />
					</a> 
				<?php }?>
			</div>
		</div>	
		<?php if($usuario->id != '') {?>
		<table>
			<tr>
				<th>Nombre</th>
				<td><?php echo  $usuario->nombre . ' ' . 
								$usuario->am . ' ' .
								$usuario->ap ?>
				</td>
			</tr>
			<tr>
				<th>Correo Electr&oacute;nico</th>
				<td>
					<a href="mailto:<?php echo $usuario->mail?>" />
					<?php echo $usuario->mail?>
					</a>
				</td>
			</tr>
			<tr>
				<th>Grupo</th>
				<td>
				<?php if(is_array($grupos)){?>
					<ul>
					<?php foreach($grupos as $grupo){?>
						<li><?php echo ucfirst($grupo)?></li>	
					<?php } ?>
					</ul>
				<?php } ?>
				</td>
			</tr>
			<tr>
				<th>Acceso</th>
				<td>
				<?php if(is_array($acceso)){?>
					<ul>
					<?php foreach ($acceso as $controlador => $vistas) {?>
						<li><strong><?php echo ucfirst($controlador) ?>: </strong>
							<?php if(is_array($vistas)){
									$i = 0;
									foreach ($vistas as $vista) {
										 echo ($i != 0 ? ', ' : '' ) . $vista;
										 $i++;
								 	} 
								  } 
							?>
						</li>
					<?php }?>
					</ul>
				<?php } ?>			
				</td>
			</tr>
		</table>
		<?php } else {?>
			<p class="error">
				<br />
			 	El usuario no existe.
			</p>
		<?php } ?>
	</div>
</div>