<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Editar ejercicio</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>ejercicios">Volver
				<img src="<?php echo $path?>public/img/system/volver.png"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>ejercicios/editar" id="frm_editar" method="post">
				<input type="hidden" name="id" id="id" value="<?php echo $ejercicio->id ?>" />
					<fieldset>
						<legend>Datos</legend>
						<label for="annio">A&ntilde;o</label>
						<br />
						<select name="annio">
							<option></option>
							<?php foreach($annios as $annio){?>
							<option value="<?php echo $annio ?>"
									<?php if($annio == $ejercicio->annio){?>selected="selected"<?php } ?>>
								<?php echo $annio ?>
							</option>
							<?php } ?>
						</select>
					</fieldset>
					<div class="divisor"></div>
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Editar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />
					La informaci&oacute;n de el ejercicio se actualiz&oacute; correctamente
				</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error">
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>