<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Editar dependencia</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>dependencias">Volver
					<img src="<?php echo $path?>public/img/system/volver.png" alt="volver"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>dependencias/editar" id="frm_editar" method="post">
					<input type="hidden" name="id" id="id" value="<?php echo $dependencia->id ?>" />
					<fieldset>
						<legend>Datos</legend>
						<label for="clave">Clave</label>
						<br />
						<input type="text" name="clave" id="clave" 
						       size="12" maxlength="12" value="<?php echo $dependencia->clave ?>"/>
				        <br />
				        <br />
						<label for="nombre">Nombre</label>
						<br />
						<input type="text" name="nombre" id="nombre" 
						       size="30" maxlength="256" value="<?php echo $dependencia->nombre ?>"/>
				        <br />
				        <br />
					</fieldset>
					<div class="divisor"></div>
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Editar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />
					La informaci&oacute;n de la dependencia se edit&oacute; correctamente
				</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error">
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>