<?php $path = KUMBIA_PATH; ?>
<div id="primary">
	<div class="content">
		<h1>Editar contacto</h1>
		<div id="options-bar">
			<div id="options">
				<a href="<?php echo $path ?>contactos">Volver
					<img src="<?php echo $path?>public/img/system/volver.png" alt="volver"/>
				</a>
			</div>
		</div>
		<?php switch($option) { 
				case 'captura': ?>
				<form action="<?php echo $path ?>contactos/editar" id="frm_editar" method="post">
					<input type="hidden" name="id" id="id" value="<?php echo $contacto->id ?>" />
					<input type="hidden" name="ejercicio_id" id="ejercicio_id" value="<?php echo $institucion->ejercicio_id ?>" />
					<fieldset>					
						<legend>Personal</legend>
						<label for="titulo">T&iacute;tulo</label>
						<br />
						<input type="text" name="titulo" id="titulo" size="5" maxlength="5" 
							   value="<?php echo htmlentities( $contacto->titulo ) ?>" />
						<br />
						<br />
						<label for="nombre">Nombre</label>
						<br />
						<input type="text" name="nombre" id="nombre" size="30" maxlength="30" 
							   value="<?php echo htmlentities( $contacto->nombre ) ?>" />
						<br />
						<br />
						<label for="ap">Apellido paterno</label>
						<br />
						<input type="text" name="ap" id="ap" size="20" maxlength="20" 
							   value="<?php echo htmlentities( $contacto->ap ) ?>" />
						<br />
						<br />
						<label for="am">Apellido materno</label>
						<br />
						<input type="text" name="am" id="am" size="20" maxlength="20" 
							   value="<?php echo htmlentities( $contacto->am ) ?>" />
						<br />
						<br />
						<label><input type="radio" name="sexo" class="sexo" value="M" id="mujer" 
								      <?php if( $contacto->sexo == 'M' ){?>checked="checked"<?php } ?> /> 
							Mujer </label>
						<label><input type="radio" name="sexo" class="sexo" value="H" id="hombre" 
								      <?php if( $contacto->sexo == 'H' ){?>checked="checked"<?php } ?> /> 
							Hombre </label><br />
					</fieldset>
					<div class="divisor"></div>
					<fieldset>
						<label><input type="radio" name="institucion" value="d" id="dependencia" 
								      <?php if( $institucion->tipo == 'dependencia' ){?>checked="checked"<?php } ?> /> 
							Dependencia </label>
						<label><input type="radio" name="institucion" value="p" id="proveedor"  
								      <?php if( $institucion->tipo == 'proveedor' ){?>checked="checked"<?php } ?> />
							Proveedor </label><br />
						<br />
						<div id="divDependencia" <?php if( $institucion->tipo != 'dependencia' ){?>style="display:none"<?php } ?> >
							<select name="dependencia_id" id="dependencia_id">
								<option />
								<?php foreach( $dependencias as $dependencia ){?>
								<option value="<?php echo $dependencia->id?>"
									<?php if( $institucion->tipo == 'dependencia' && $institucion->id == $dependencia->id ){?>selected="selected"<?php } ?>>
									<?php echo $dependencia->clave . ' / ' . $dependencia->nombre ?>
								</option>
								<?php } ?>
							</select>
						</div>
						<div id="divProveedor"  <?php if( $institucion->tipo != 'proveedor' ){?>style="display:none"<?php } ?>>
							<select name="proveedor_id" id="proveedor_id">
								<option />
								<?php foreach( $proveedores as $proveedor ){?>
								<option value="<?php echo $proveedor->id?>"
									<?php if( $institucion->tipo == 'proveedor' && $institucion->id == $proveedor->id ){?>selected="selected"<?php } ?>>
									<?php echo $proveedor->nombre ?>
								</option>
								<?php } ?>
							</select>
						</div>
						<legend>Laboral</legend>
						<label for="cargo">Cargo</label>
						<br />
						<input type="text" name="cargo" id="cargo" size="30" maxlength="30"  
							   value="<?php echo $contacto->cargo ?>"/>
						<br />
						<br />
					</fieldset>
					<div class="divisor"></div>
					<fieldset>		
						<label for="domicilio">Domicilio</label>
						<br />
						<input type="text" name="domicilio" id="domicilio" size="30" maxlength="254"  
							   value="<?php echo htmlentities( $contacto->domicilio ) ?>" />
						<br />
						<br />			
						<legend>Contacto</legend>
						<label for="tel">Tel&eacute;fono</label>
						<br />
						<input type="text" name="tel" id="tel" size="30" maxlength="30"  
							   value="<?php echo htmlentities( $contacto->tel ) ?>"/>
						<br />
						<br />
						<label for="cel">Tel&eacute;fono m&oacute;vil</label>
						<br />
						<input type="text" name="cel" id="cel" size="30" maxlength="30"  
							   value="<?php echo htmlentities( $contacto->cel ) ?>"/>
						<br />
						<br />
						<label for="trunk">Radio</label>
						<br />
						<input type="text" name="trunk" id="trunk" size="30" maxlength="30"  
							   value="<?php echo htmlentities( $contacto->trunk ) ?>"/>
						<br />
						<br />
						<label for="mail">Correo electr&oacute;nico</label>
						<br />
						<input type="text" name="mail" id="mail" size="40" maxlength="60"  
							   value="<?php echo htmlentities( $contacto->mail ) ?>"/>
						<br />
						<br />
						<label for="observaciones">Observaciones</label>
						<br />
						<input type="text" name="observaciones" id="observaciones" size="40" maxlength="256"  
							   value="<?php echo htmlentities( $contacto->observaciones ) ?>"/>
						<br />
						<br />
					</fieldset>
					<div class="divisor"></div>
					<div id="botones">
						<input type="button" id="cancelar" value="Cancelar">
						<input type="button" id="aceptar" value="Editar">
					</div>
				</form>
			<?php  break; ?>
			<?php case 'exito': ?>
				<p class="info">
					<br />
					La informaci&oacute;n del contacto se edit&oacute; correctamente
				</p>
			<?php  break; ?>
			<?php case 'error': 
				  default: 
			?>
				<p class="error">
					<br />
					<?php echo $error ?>
				</p>
			<?php  break; ?>
		<?php } ?>
	</div>
</div>