<div id="primary">
	<div class="content">
		<form action="<?php echo KUMBIA_PATH ?>sesion/abrir" method="post" id="frm_auth">
			<fieldset>
				<legend>Iniciar sesi&oacute;n</legend>
				<div>
					<label for="login">Usuario</label>
					<input name="login" id="login" type="text" size="15" maxlength="25"  />
				</div>
				<div>
					<label for="pass">Contrase&ntilde;a</label>
					<input name="pass" type="password" id="pass" size="15" maxlength="25" />
				</div>
				<input type="submit" id="aceptar" value=".: Entrar" />
			</fieldset>
		</form>
		<?php if($evento == sha1('err_login')){ ?>
		<p class="error"><br />Nombre de usuario o contrase&ntilde;a incorrecta</p>
		<?php } ?>
	</div>
</div>
<div id="secondary"><div class="content"></div></div>
<div id="tertiary"><div class="content"></div></div>